package com.guideforwinjo.winzogoldwin.tipswinzo.Activity;

import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.SearchView;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.guideforwinjo.winzogoldwin.tipswinzo.ADS.Ads;
import com.guideforwinjo.winzogoldwin.tipswinzo.ADS.BannerAds;
import com.guideforwinjo.winzogoldwin.tipswinzo.Adapter.SeachGameitemAdapter;
import com.guideforwinjo.winzogoldwin.tipswinzo.Model.Games;
import com.guideforwinjo.winzogoldwin.R;
import com.squareup.picasso.Picasso;

import java.util.ArrayList;

import static com.guideforwinjo.winzogoldwin.tipswinzo.First.FirstActivity.sharedPreferences;

public class earchGameActivity extends AppCompatActivity implements SearchView.OnQueryTextListener {

    private ArrayList<Games> Gamelist;
    private SeachGameitemAdapter adapter;
    private RecyclerView.LayoutManager mLayoutManager;
    private RecyclerView rvLista;
    private SearchView svSearch;
    View view;

    CardView costom;
    private int counter = 3;
    private int counter2 = 4;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search_game);

        BannerAds.showBannerAds(this, (LinearLayout) findViewById(R.id.banner_ad_container));

        ImageView appicon = (ImageView) findViewById(R.id.appicon);
        TextView appname = (TextView) findViewById(R.id.appname);

        try {
            Picasso.with(earchGameActivity.this).load(Ads.imagegallary.get(counter))
                    .into(appicon);
            appname.setText(Ads.name.get(counter));
            appname.setSelected(true);
        } catch (Exception e) {
        }

        costom = findViewById(R.id.costom);
        String costomad = sharedPreferences.getString("costomad", "");
        if (costomad.equalsIgnoreCase("on")) {
            costom.setVisibility(View.VISIBLE);
            costom.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    try {
                        Picasso.with(earchGameActivity.this).load(Ads.imagegallary.get(counter2))
                                .into(appicon);
                        appname.setText(Ads.name.get(counter2));
                        appname.setSelected(true);
                    } catch (Exception e) {
                    }
                    gotoAppStore(Ads.link.get(counter));
                    counter++;
                    counter2++;
                    if (counter == Ads.imagegallary.size()) {
                        counter = 0;
                    }
                    if (counter2 == Ads.imagegallary.size()) {
                        counter2 = 0;
                    }
//                    startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(sharedPreferences.getString("costompk",""))));
                }
            });
        }

        this.rvLista = findViewById(R.id.rvListaf);
        this.svSearch = findViewById(R.id.svSearchf);

        this.rvLista.setLayoutManager(new GridLayoutManager(this, 3));
        ArrayList<Games> items = getItems();
        this.Gamelist = items;
        SeachGameitemAdapter blueSeachGameitemAdapter = new SeachGameitemAdapter(items, this);
        this.adapter = blueSeachGameitemAdapter;
        this.rvLista.setAdapter(blueSeachGameitemAdapter);
        this.svSearch.setOnQueryTextListener(this);
    }

    private void gotoAppStore(final String packagename) {
        try {
            startActivity(new Intent(
                    Intent.ACTION_VIEW,
                    Uri.parse(packagename)));
        } catch (ActivityNotFoundException anfe) {
            startActivity(new Intent(
                    Intent.ACTION_VIEW,
                    Uri.parse(packagename)));
        }
    }


    public boolean onQueryTextSubmit(String str) {
        return false;
    }

    @Override
    public boolean onQueryTextChange(String str) {
        this.adapter.filter(str);
        return false;
    }

    private ArrayList<Games> getItems() {
        ArrayList<Games> arrayList = new ArrayList<>();

        String quezop_url = sharedPreferences.getString("quezop_url", "");
        String gamezop_url = sharedPreferences.getString("gamezop_url", "");

        arrayList.add(new Games("Air Hockeyir ", quezop_url, R.drawable.a1a));
        arrayList.add(new Games("Air Warfare ", gamezop_url, R.drawable.a2a));
        arrayList.add(new Games("Assassin Knight ", quezop_url, R.drawable.a6a));
        arrayList.add(new Games("Mad Shark ", gamezop_url, R.drawable.a53a));
        arrayList.add(new Games("Cyber Slashman ", quezop_url, R.drawable.a21a));
        arrayList.add(new Games("Cyber Soldier ", gamezop_url, R.drawable.a22a));
        arrayList.add(new Games("Defence Champion ", quezop_url, R.drawable.a26));
        arrayList.add(new Games("Shoot Robbers ", gamezop_url, R.drawable.a70a));
        arrayList.add(new Games("Fishing Frenzy ", quezop_url, R.drawable.a31a));
        arrayList.add(new Games(" Great-Air Battles", gamezop_url, R.drawable.a42a));
        arrayList.add(new Games("Tank Defender ", quezop_url, R.drawable.a82a));
        arrayList.add(new Games("Tank Wars ", gamezop_url, R.drawable.a83a));
        arrayList.add(new Games("Duck Shooter ", quezop_url, R.drawable.a28a));
        arrayList.add(new Games("Duosometric Jump ", gamezop_url, R.drawable.a29a));
        arrayList.add(new Games("Duck Hunter ", quezop_url, R.drawable.a27a));
        arrayList.add(new Games("Alien-Hunter 2 ", gamezop_url, R.drawable.a3a));
        arrayList.add(new Games(" Strike Expert", quezop_url, R.drawable.a78a));
        arrayList.add(new Games("Gold Miner ", quezop_url, R.drawable.a40a));
        arrayList.add(new Games("Fire Soldier ", gamezop_url, R.drawable.a30a));
        arrayList.add(new Games(" Gold-Miner Jack", quezop_url, R.drawable.a41a));
        arrayList.add(new Games("Fruitslasher", gamezop_url, R.drawable.a36a));
        arrayList.add(new Games("Fruit Snake ", quezop_url, R.drawable.a35a));
        arrayList.add(new Games("Dead-Land-Adventure 2 ", gamezop_url, R.drawable.a25a));
        arrayList.add(new Games("Defence Champion ", quezop_url, R.drawable.a26a));
        arrayList.add(new Games("Joee Adventure ", gamezop_url, R.drawable.a47a));
        arrayList.add(new Games("Jump Jump ", quezop_url, R.drawable.a48a));
        arrayList.add(new Games("Playful Kitty ", gamezop_url, R.drawable.a60a));
        arrayList.add(new Games(" Plumber", quezop_url, R.drawable.a61a));
        arrayList.add(new Games("Piggybank Adventure ", gamezop_url, R.drawable.a59a));
        arrayList.add(new Games("Flappy Pig", quezop_url, R.drawable.a32a));
        arrayList.add(new Games("Ninja Run ", gamezop_url, R.drawable.a57a));
        arrayList.add(new Games("Floor-Jumper Escape ", quezop_url, R.drawable.a33a));
        arrayList.add(new Games("Stack Jump ", gamezop_url, R.drawable.a74a));
        arrayList.add(new Games("Stick Monkey ", quezop_url, R.drawable.a75a));
        arrayList.add(new Games("Dashers ", gamezop_url, R.drawable.a24a));
        arrayList.add(new Games(" Stick Panda", quezop_url, R.drawable.a76a));
        arrayList.add(new Games(" Zoo Run", gamezop_url, R.drawable.a94a));
        arrayList.add(new Games(" Cars", quezop_url, R.drawable.a16a));
        arrayList.add(new Games(" Crazy Runner", quezop_url, R.drawable.a17a));
        arrayList.add(new Games("Cube Ninja ", gamezop_url, R.drawable.a20a));
        arrayList.add(new Games("Road Racer ", quezop_url, R.drawable.a66a));
        arrayList.add(new Games(" Santa Run", gamezop_url, R.drawable.a68a));
        arrayList.add(new Games("Scary Run ", quezop_url, R.drawable.a69a));
        arrayList.add(new Games("Speed Racer ", gamezop_url, R.drawable.a72a));
        arrayList.add(new Games(" Speedy Driving", quezop_url, R.drawable.a73a));
        arrayList.add(new Games("Traffic ", gamezop_url, R.drawable.a85a));
        arrayList.add(new Games("Traffic Command ", quezop_url, R.drawable.a86a));
        arrayList.add(new Games("Truck-Parking Pro ", gamezop_url, R.drawable.a87a));
        arrayList.add(new Games("Dark Ninja ", quezop_url, R.drawable.a23a));
        arrayList.add(new Games(" Creepy Day", gamezop_url, R.drawable.a18a));
        arrayList.add(new Games(" Cube Dash", quezop_url, R.drawable.a19a));
        arrayList.add(new Games("Alien Galaxy War ", gamezop_url, R.drawable.u150));
        arrayList.add(new Games(" highway-rider-extreme", quezop_url, R.drawable.u71));
        arrayList.add(new Games(" Viking Attack", gamezop_url, R.drawable.a88a));
        arrayList.add(new Games("Viking Escape ", quezop_url, R.drawable.a89a));
        arrayList.add(new Games(" Vikings-Vs Skeletons", gamezop_url, R.drawable.a90a));
        arrayList.add(new Games("Wothan Escape ", quezop_url, R.drawable.a91a));
        arrayList.add(new Games(" Zombie Buster", gamezop_url, R.drawable.a92a));
        arrayList.add(new Games("Zombie Shooter ", quezop_url, R.drawable.a93a));
        arrayList.add(new Games("Super-Cowboy Run ", gamezop_url, R.drawable.a80a));
        arrayList.add(new Games("Ranger-Vs Zombies ", quezop_url, R.drawable.a65a));
        arrayList.add(new Games("Knife-Vs Zombies\t ", gamezop_url, R.drawable.a51a));
        arrayList.add(new Games("Mad Scientist ", quezop_url, R.drawable.a52a));
        arrayList.add(new Games("Swat-Vs Zombies ", gamezop_url, R.drawable.a81a));
        arrayList.add(new Games("The-Bandit Hunter ", quezop_url, R.drawable.a84a));
        arrayList.add(new Games("Basketball ", gamezop_url, R.drawable.a8a));
        arrayList.add(new Games("Billiards ", gamezop_url, R.drawable.a9a));
        arrayList.add(new Games("Air Hockeyir ", quezop_url, R.drawable.a1a));
        arrayList.add(new Games("Monster-Truck Football\t ", gamezop_url, R.drawable.a55a));
        arrayList.add(new Games("Pool-8 Ball ", quezop_url, R.drawable.a62a));
        arrayList.add(new Games("Stickman-Table Tennis ", gamezop_url, R.drawable.a77a));
        arrayList.add(new Games(" Pops Billiards", quezop_url, R.drawable.a63a));
        arrayList.add(new Games("Supe-Pon Goal ", gamezop_url, R.drawable.a79a));
        arrayList.add(new Games("Penalty Challenge ", quezop_url, R.drawable.a58a));
        arrayList.add(new Games("Space Purge", gamezop_url, R.drawable.a71a));
        arrayList.add(new Games(" Barn Dash", quezop_url, R.drawable.a7a));
        arrayList.add(new Games("Jumpers Jumpers ", gamezop_url, R.drawable.a49a));
        arrayList.add(new Games("Jungle Treasure", quezop_url, R.drawable.a50a));

        arrayList.add(new Games("Avengers Game", quezop_url, R.drawable.mo2));
        arrayList.add(new Games("Worms.zone.io", quezop_url, R.drawable.mo3));
        arrayList.add(new Games(" Relicrunway", gamezop_url, R.drawable.mo4));
        arrayList.add(new Games("Temple Run 2", quezop_url, R.drawable.mo6));
        arrayList.add(new Games("Slither Vs Block", gamezop_url, R.drawable.mo7));
        arrayList.add(new Games("Master Chess", quezop_url, R.drawable.mo8));
        arrayList.add(new Games("Master_checkers", gamezop_url, R.drawable.mo5));
        arrayList.add(new Games("9 Ball Pool", quezop_url, R.drawable.mo9));
        arrayList.add(new Games("Ludo With Friends", gamezop_url, R.drawable.mo10));
        arrayList.add(new Games("Real Garbage Truck", quezop_url, R.drawable.o1));
        arrayList.add(new Games("PUBG MOBILE", gamezop_url, R.drawable.o2));
        arrayList.add(new Games("Among Us Shooter", quezop_url, R.drawable.o3));
        arrayList.add(new Games("Balloons Creator", gamezop_url, R.drawable.o4));
        arrayList.add(new Games("Talking Tom Cat 2", quezop_url, R.drawable.o8));
        arrayList.add(new Games("TOM AND ANGELA DINNER", gamezop_url, R.drawable.o5));
        arrayList.add(new Games("ANGELAS CLOSET", quezop_url, R.drawable.o6));
        arrayList.add(new Games("PREGNANT ANGELA AMBULANCE", gamezop_url, R.drawable.o7));
        arrayList.add(new Games("Badminton", quezop_url, R.drawable.o9));
        arrayList.add(new Games("Hunter Assassin", gamezop_url, R.drawable.o10));
        arrayList.add(new Games("Stack-smash", quezop_url, R.drawable.mo12));
        arrayList.add(new Games("Snake Pro", gamezop_url, R.drawable.mo14));
        arrayList.add(new Games("Penalty_challenge", quezop_url, R.drawable.mo13));
        arrayList.add(new Games("hooligans", gamezop_url, R.drawable.mo15));
        arrayList.add(new Games("Snake Blast", quezop_url, R.drawable.mo16));
        arrayList.add(new Games("Domino", gamezop_url, R.drawable.mo17));
        arrayList.add(new Games("Angry birds 2", quezop_url, R.drawable.mo18));
        arrayList.add(new Games("Jungle Merga", gamezop_url, R.drawable.mo1));
        arrayList.add(new Games("Fatao", quezop_url, R.drawable.mo20));
        arrayList.add(new Games("Pool-8-ball", gamezop_url, R.drawable.mo22));
        arrayList.add(new Games("Defend the Den", quezop_url, R.drawable.mo24));
        arrayList.add(new Games("Tost Treasures   ", gamezop_url, R.drawable.mo25));
        arrayList.add(new Games("DuckPark io", quezop_url, R.drawable.mo26));
        arrayList.add(new Games("Sailorpop", gamezop_url, R.drawable.mo27));
        arrayList.add(new Games("ROPE NINJA", quezop_url, R.drawable.mo28));
        arrayList.add(new Games("Jelly Escape ", gamezop_url, R.drawable.mo29));
        arrayList.add(new Games("Moto-x3m-spooky-land", quezop_url, R.drawable.mo31));
        arrayList.add(new Games("Crazy-runner", gamezop_url, R.drawable.mo32));
        arrayList.add(new Games("Neon Bricks", quezop_url, R.drawable.mo33));
        arrayList.add(new Games("Swipe-basketball", gamezop_url, R.drawable.mo34));
        arrayList.add(new Games("Stack-bump-3d", quezop_url, R.drawable.mo35));
        arrayList.add(new Games("Cut-the-rope", gamezop_url, R.drawable.mo36));
        arrayList.add(new Games("ludo-king", quezop_url, R.drawable.mo37));
        arrayList.add(new Games("Yeti Sensation", quezop_url, R.drawable.a1));
        arrayList.add(new Games("Chop Chop slice-rush     ", gamezop_url, R.drawable.a30));
        arrayList.add(new Games("Cut-The-Rope     ", quezop_url, R.drawable.a31));
        arrayList.add(new Games("Ludu King", gamezop_url, R.drawable.a2));
        arrayList.add(new Games(" The Shootout : Saloon", quezop_url, R.drawable.a4));
        arrayList.add(new Games("Subway Runer      ", gamezop_url, R.drawable.a5));
        arrayList.add(new Games(" Fruits Ninja", quezop_url, R.drawable.a6));
        arrayList.add(new Games("Santa City Run", gamezop_url, R.drawable.a7));
        arrayList.add(new Games("The Private Ship", quezop_url, R.drawable.a8));
        arrayList.add(new Games("Slinguin", gamezop_url, R.drawable.a9));
        arrayList.add(new Games("Snakes & Ladders", quezop_url, R.drawable.a10));
        arrayList.add(new Games("Viking Escape ", gamezop_url, R.drawable.a89a));
        arrayList.add(new Games("Soldiers-Combat", quezop_url, R.drawable.a12));
        arrayList.add(new Games("Fruit-Master", gamezop_url, R.drawable.a13));
        arrayList.add(new Games("Fishing-frenzy", quezop_url, R.drawable.a14));
        arrayList.add(new Games("Duck-hunter", gamezop_url, R.drawable.a15));
        arrayList.add(new Games("Mad-shark", quezop_url, R.drawable.a16));
        arrayList.add(new Games("Snake-attack ", gamezop_url, R.drawable.a17));
        arrayList.add(new Games("mummy-candies", quezop_url, R.drawable.a18));
        arrayList.add(new Games("Santa-run", gamezop_url, R.drawable.a19));
        arrayList.add(new Games("Shoot-robbers ", quezop_url, R.drawable.a20));
        arrayList.add(new Games(" KnifeBreak  ", gamezop_url, R.drawable.a21));
        arrayList.add(new Games("TropicPirateTreasure", quezop_url, R.drawable.a22));
        arrayList.add(new Games(" KnifeFlip", gamezop_url, R.drawable.a23));
        arrayList.add(new Games(" KungFuMaster", quezop_url, R.drawable.a24));
        arrayList.add(new Games("Archery", gamezop_url, R.drawable.a25));
        arrayList.add(new Games("DontCutYourself", quezop_url, R.drawable.a26));
        arrayList.add(new Games("ApachiriRun", gamezop_url, R.drawable.a27));
        arrayList.add(new Games("Fruit-slasher ", quezop_url, R.drawable.a29));
        arrayList.add(new Games("E.T", gamezop_url, R.drawable.a28));
        arrayList.add(new Games("lone-pistol-zombies-in-the-streets", quezop_url, R.drawable.z1));
        arrayList.add(new Games("ZOMBIES CAN’T JUMP", gamezop_url, R.drawable.z2));
        arrayList.add(new Games("  Zombie-buster", quezop_url, R.drawable.z3));
        arrayList.add(new Games("Ranger-vs-zombies", gamezop_url, R.drawable.z4));
        arrayList.add(new Games("Ranger-vs-zombies ", quezop_url, R.drawable.z5));
        arrayList.add(new Games("SWAT Vs Zombie", gamezop_url, R.drawable.z6));
        arrayList.add(new Games("Zombie Shooter ", quezop_url, R.drawable.a93a));
        arrayList.add(new Games("Mad-Scientist", gamezop_url, R.drawable.z7));
        arrayList.add(new Games("Viking-Escape", quezop_url, R.drawable.z9));
        arrayList.add(new Games("Bones-slasher", gamezop_url, R.drawable.z11));
        arrayList.add(new Games("Zombie Can't Jump 2", quezop_url, R.drawable.z10));
        arrayList.add(new Games("Invader-zim-doom-game", gamezop_url, R.drawable.z12));
        arrayList.add(new Games("Defend the den", quezop_url, R.drawable.z14));
        arrayList.add(new Games("Run-Into-Death", gamezop_url, R.drawable.z15));
        arrayList.add(new Games("Super-cowboy-run", quezop_url, R.drawable.z21));
        arrayList.add(new Games("ZombieSmash", gamezop_url, R.drawable.z16));
        arrayList.add(new Games("Cowboy-shoot-zombies", quezop_url, R.drawable.z17));
        arrayList.add(new Games("Zombie-uprising", gamezop_url, R.drawable.z18));
        arrayList.add(new Games("skulls-vs-zombies", quezop_url, R.drawable.z19));
        arrayList.add(new Games("  SAVE THE MONSTERS ", gamezop_url, R.drawable.z20));
        arrayList.add(new Games("Avengers2", quezop_url, R.drawable.mu1));
        arrayList.add(new Games("Ludo legend", gamezop_url, R.drawable.mu2));
        arrayList.add(new Games("Master_checkers", quezop_url, R.drawable.mu3));
        arrayList.add(new Games("Ultimate_boxing", gamezop_url, R.drawable.mu4));
        arrayList.add(new Games("Ultimate_swish", quezop_url, R.drawable.mu6));
        arrayList.add(new Games("Mini-jumper", gamezop_url, R.drawable.mu7));
        arrayList.add(new Games("http://slither.io/", quezop_url, R.drawable.mu9));
        arrayList.add(new Games("Billiards ", gamezop_url, R.drawable.a9a));
        arrayList.add(new Games(" Night Ride", quezop_url, R.drawable.mu10));
        arrayList.add(new Games("9 Ball Pool", gamezop_url, R.drawable.mu11));
        arrayList.add(new Games("Sweet-candy-saga 2", quezop_url, R.drawable.pu1));
        arrayList.add(new Games("Christmas_shooter_50", gamezop_url, R.drawable.pu3));
        arrayList.add(new Games("Christmas_chain", quezop_url, R.drawable.pu4));
        arrayList.add(new Games("Halloween_chain", gamezop_url, R.drawable.pu5));
        arrayList.add(new Games("Halloween_breaker", quezop_url, R.drawable.pu6));
        arrayList.add(new Games("Stickman Rope", gamezop_url, R.drawable.pu7));
        arrayList.add(new Games("Spacebubbles", quezop_url, R.drawable.pu8));
        arrayList.add(new Games("Christmas-match-3", gamezop_url, R.drawable.pu9));
        arrayList.add(new Games("Christmas-panda-run", quezop_url, R.drawable.pu10));
        arrayList.add(new Games("JELLY DOODS", gamezop_url, R.drawable.pu11));
        arrayList.add(new Games("Fish-world-match-3", quezop_url, R.drawable.pu12));
        arrayList.add(new Games("Ultimate-sodoku", gamezop_url, R.drawable.pu13));
        arrayList.add(new Games("Supercars-puzzl", quezop_url, R.drawable.pu27));
        arrayList.add(new Games("Easter-memory", gamezop_url, R.drawable.pu14));
        arrayList.add(new Games("Professor-bubble", quezop_url, R.drawable.pu15));
        arrayList.add(new Games("Free-words", gamezop_url, R.drawable.pu16));
        arrayList.add(new Games("Happy-hallowee", quezop_url, R.drawable.pu17));
        arrayList.add(new Games(" Gold-miner-jack", gamezop_url, R.drawable.pu18));
        arrayList.add(new Games("Halloween-bubble-shooter", quezop_url, R.drawable.pu18));
        arrayList.add(new Games("Bubbles Five ", gamezop_url, R.drawable.pu20));
        arrayList.add(new Games("4 pics 1 word", quezop_url, R.drawable.pu21));
        arrayList.add(new Games("LittleWorldJellys", gamezop_url, R.drawable.pu22));
        arrayList.add(new Games("NutsForWinter", quezop_url, R.drawable.pu23));
        arrayList.add(new Games("CandyConnect", gamezop_url, R.drawable.pu24));
        arrayList.add(new Games("Bubble-shoote ", quezop_url, R.drawable.pu25));
        arrayList.add(new Games("Jelly-match-3", gamezop_url, R.drawable.pu26));
        arrayList.add(new Games("Brick-out", quezop_url, R.drawable.pu29));
        arrayList.add(new Games("Candy-super-lines ", gamezop_url, R.drawable.pu30));
        arrayList.add(new Games("Cartoon-candy", quezop_url, R.drawable.pu31));
        arrayList.add(new Games("Crazy-jump-3 ", gamezop_url, R.drawable.pu32));
        arrayList.add(new Games("Crazy-match", quezop_url, R.drawable.pu32));
        arrayList.add(new Games("Frog-super-bubbles", gamezop_url, R.drawable.pu33));
        arrayList.add(new Games("Angry-cat-shot ", quezop_url, R.drawable.pu28));
        arrayList.add(new Games("Indian Truck Simulator 3D", gamezop_url, R.drawable.si1));
        arrayList.add(new Games("Aircraft Flying Simulator", quezop_url, R.drawable.si3));
        arrayList.add(new Games("Watercraft_rus", gamezop_url, R.drawable.si5));
        arrayList.add(new Games("Hill Climber", quezop_url, R.drawable.si6));
        arrayList.add(new Games("Asro Knot", gamezop_url, R.drawable.si7));
        arrayList.add(new Games("Drive Boad", quezop_url, R.drawable.si8));
        arrayList.add(new Games("Train Snake", gamezop_url, R.drawable.si9));
        arrayList.add(new Games("SantasLastMinutePresents", quezop_url, R.drawable.si10));
        arrayList.add(new Games("TajisClimb", gamezop_url, R.drawable.si11));
        arrayList.add(new Games("Cars", quezop_url, R.drawable.si12));
        arrayList.add(new Games("Finger-drift", gamezop_url, R.drawable.si13));
        arrayList.add(new Games("Crazy-car", quezop_url, R.drawable.si14));
        arrayList.add(new Games("Math-game-for-kids", gamezop_url, R.drawable.si15));
        arrayList.add(new Games("Mini-racer", quezop_url, R.drawable.si16));
        arrayList.add(new Games("Road-racer", gamezop_url, R.drawable.si17));
        arrayList.add(new Games("Lost Treasures         ", quezop_url, R.drawable.ad1));
        arrayList.add(new Games("PEBBLE BOY         ", gamezop_url, R.drawable.ad2));
        arrayList.add(new Games("Mine Clone 4          ", quezop_url, R.drawable.ad3));
        arrayList.add(new Games("Rabbit Samurai         ", gamezop_url, R.drawable.ad4));
        arrayList.add(new Games("3D Bottle Shoter          ", quezop_url, R.drawable.ad5));
        arrayList.add(new Games("Armored Blaster     ", gamezop_url, R.drawable.ad6));
        arrayList.add(new Games("Colours Magnet       ", quezop_url, R.drawable.ad7));
        arrayList.add(new Games("Frolic  car Parking    ", gamezop_url, R.drawable.ad8));
        arrayList.add(new Games("Build And Protected         ", quezop_url, R.drawable.ad10));
        arrayList.add(new Games("Pie .ai        ", gamezop_url, R.drawable.ad12));
        arrayList.add(new Games("Stack Tower         ", quezop_url, R.drawable.ad13));
        arrayList.add(new Games("Gold-miner      ", gamezop_url, R.drawable.ad14));
        arrayList.add(new Games("Bouncing Squirrel       ", quezop_url, R.drawable.ad15));
        arrayList.add(new Games(" Physics BTR        ", gamezop_url, R.drawable.ad16));
        arrayList.add(new Games("Sand Worm          ", quezop_url, R.drawable.ad17));
        arrayList.add(new Games("Tap Dash Tap        ", gamezop_url, R.drawable.ad18));
        arrayList.add(new Games("BallIn The Cup        ", quezop_url, R.drawable.ad19));
        arrayList.add(new Games("Ice Cream         ", gamezop_url, R.drawable.ad20));
        arrayList.add(new Games("Hungry Frog       ", quezop_url, R.drawable.ad21));
        arrayList.add(new Games("Mario-Adventure-Worlds         ", gamezop_url, R.drawable.ad22));
        arrayList.add(new Games("Crazy-jump-3 ", quezop_url, R.drawable.ad23));
        arrayList.add(new Games("Rocket Road    ", gamezop_url, R.drawable.th1));
        arrayList.add(new Games("Helix-jump    ", quezop_url, R.drawable.th2));
        arrayList.add(new Games("Flip-It    ", gamezop_url, R.drawable.th3));
        arrayList.add(new Games("3d-bottle-shooter   ", quezop_url, R.drawable.th4));
        arrayList.add(new Games("Rush-3d2   ", gamezop_url, R.drawable.th5));
        arrayList.add(new Games("3D-Rubiks-cube ", quezop_url, R.drawable.th6));
        arrayList.add(new Games("Ball jump   ", gamezop_url, R.drawable.th7));
        arrayList.add(new Games("Break-the-cup    ", quezop_url, R.drawable.th8));
        arrayList.add(new Games("Blaze Dragon island Race  ", gamezop_url, R.drawable.th9));
        arrayList.add(new Games("Taable tennis      ", quezop_url, R.drawable.th10));
        arrayList.add(new Games("Knife Up    ", gamezop_url, R.drawable.th11));
        arrayList.add(new Games("DuckPark Io   ", quezop_url, R.drawable.th12));
        arrayList.add(new Games(" Rollout  ", gamezop_url, R.drawable.th13));
        arrayList.add(new Games("Colour Tower 2   ", quezop_url, R.drawable.th14));
        arrayList.add(new Games("Run Rase 3d 2   ", gamezop_url, R.drawable.th15));
        arrayList.add(new Games("Run Rase   ", quezop_url, R.drawable.th16));
        arrayList.add(new Games("Hyper Jump 3D   ", gamezop_url, R.drawable.th17));
        arrayList.add(new Games("Limit Carve  ", quezop_url, R.drawable.th18));
        arrayList.add(new Games("Stack-bump-3d  ", gamezop_url, R.drawable.th19));
        arrayList.add(new Games("Space Attack         ", quezop_url, R.drawable.ar1));
        arrayList.add(new Games("Air-fight        ", gamezop_url, R.drawable.ar2));
        arrayList.add(new Games("air_force_2020          ", quezop_url, R.drawable.ar3));
        arrayList.add(new Games("Air War        ", gamezop_url, R.drawable.ar4));
        arrayList.add(new Games("Air Force Flight        ", quezop_url, R.drawable.ar6));
        arrayList.add(new Games("Air Comrat       ", gamezop_url, R.drawable.ar7));
        arrayList.add(new Games("Fly or Die         ", quezop_url, R.drawable.ar8));
        arrayList.add(new Games("Air  Speck          ", gamezop_url, R.drawable.ar9));
        arrayList.add(new Games("Waste invader       ", quezop_url, R.drawable.ar10));
        arrayList.add(new Games("Space blaze DX         ", gamezop_url, R.drawable.ar11));
        arrayList.add(new Games("Air Batteship force         ", quezop_url, R.drawable.ar12));
        arrayList.add(new Games("Air animal Force ff         ", gamezop_url, R.drawable.ar13));
        arrayList.add(new Games("Duck shooter           ", quezop_url, R.drawable.ar14));
        arrayList.add(new Games("WesternSheriff       ", gamezop_url, R.drawable.ar15));
        arrayList.add(new Games("AttackOnHumans       ", quezop_url, R.drawable.ar16));
        arrayList.add(new Games("Amelia Dress-Up    ", quezop_url, R.drawable.gl1));
        arrayList.add(new Games("Wonderlan fairy princess   ", gamezop_url, R.drawable.gl2));
        arrayList.add(new Games("Mommy BFFs Preganant check Up   ", quezop_url, R.drawable.gl13));
        arrayList.add(new Games("Winter lockBook   ", gamezop_url, R.drawable.gl4));
        arrayList.add(new Games("Waking sleeping beauty    ", quezop_url, R.drawable.gl5));
        arrayList.add(new Games("Princess-mermaid-accident-er   ", gamezop_url, R.drawable.gl6));
        arrayList.add(new Games("Wow Girl    ", quezop_url, R.drawable.gl7));
        arrayList.add(new Games("Pizza Relife Cookig   ", gamezop_url, R.drawable.gl8));
        arrayList.add(new Games("Disney Princess makeover  ", quezop_url, R.drawable.gl9));
        arrayList.add(new Games("DentistDoctor Teeth   ", gamezop_url, R.drawable.gl10));
        arrayList.add(new Games("Avocado Toast instagram     ", quezop_url, R.drawable.gl11));
        arrayList.add(new Games("Legendary fashion   ", gamezop_url, R.drawable.gl12));
        arrayList.add(new Games("Sandwich baker   ", quezop_url, R.drawable.gl13));
        arrayList.add(new Games("Girl-dress-up   ", gamezop_url, R.drawable.gl14));
        arrayList.add(new Games("Rasing Stary   ", gamezop_url, R.drawable.sp1));
        arrayList.add(new Games("CPL-tournament  ", quezop_url, R.drawable.sp2));
        arrayList.add(new Games("highway-rider-extreme    ", gamezop_url, R.drawable.sp3));
        arrayList.add(new Games("Weely 3   ", quezop_url, R.drawable.sp4));
        arrayList.add(new Games("Touchdown_rush    ", gamezop_url, R.drawable.sp5));
        arrayList.add(new Games("Cricket_batter_challenge    ", quezop_url, R.drawable.sp6));
        arrayList.add(new Games("Funny_soccer  ", gamezop_url, R.drawable.sp8));
        arrayList.add(new Games("Rollout  ", quezop_url, R.drawable.sp9));
        arrayList.add(new Games("Wrestle Online   ", gamezop_url, R.drawable.sp10));
        arrayList.add(new Games("Swipe-basketball    ", quezop_url, R.drawable.sp11));
        arrayList.add(new Games("Flappy-ball    ", gamezop_url, R.drawable.sp12));
        arrayList.add(new Games("Flappy-bounce    ", quezop_url, R.drawable.sp13));
        arrayList.add(new Games("FortuneBall  ", gamezop_url, R.drawable.sp14));
        arrayList.add(new Games("PatrolBypass    ", quezop_url, R.drawable.sp15));
        arrayList.add(new Games(" FootballHeroes    ", gamezop_url, R.drawable.sp16));
        arrayList.add(new Games("Touch-ball  ", quezop_url, R.drawable.sp17));
        arrayList.add(new Games("Super-pongoal ", gamezop_url, R.drawable.sp18));
        arrayList.add(new Games(" Pool-8-ball ", quezop_url, R.drawable.sp19));
        arrayList.add(new Games("Neon-hockey  ", gamezop_url, R.drawable.sp20));
        arrayList.add(new Games(" Cricket-fielder-challenge", quezop_url, R.drawable.sp21));
        arrayList.add(new Games("Cricket-batter-challenge ", gamezop_url, R.drawable.sp22));
        arrayList.add(new Games("Hill-climb-racing-3   ", quezop_url, R.drawable.ra1));
        arrayList.add(new Games("Save the Egg   ", gamezop_url, R.drawable.ra2));
        arrayList.add(new Games("Paper racers Boomerang     ", quezop_url, R.drawable.ra3));
        arrayList.add(new Games("Up-hill-racing   ", gamezop_url, R.drawable.ra4));
        arrayList.add(new Games("Gear_madness    ", quezop_url, R.drawable.ra5));
        arrayList.add(new Games("Moto Cruiser Highway   ", gamezop_url, R.drawable.ra6));
        arrayList.add(new Games("Rocking_wheels    ", quezop_url, R.drawable.ra7));
        arrayList.add(new Games("Water Slides.io   ", gamezop_url, R.drawable.ra8));
        arrayList.add(new Games("Moto_beach_rider   ", quezop_url, R.drawable.ra9));
        arrayList.add(new Games("Uphill Bus Simulator   ", gamezop_url, R.drawable.ra10));
        arrayList.add(new Games("Burnin-rubbe   ", quezop_url, R.drawable.ra11));
        arrayList.add(new Games("Horse_racing  ", gamezop_url, R.drawable.ra12));
        arrayList.add(new Games("Car_rush   ", quezop_url, R.drawable.ra13));
        arrayList.add(new Games("Drive_your_car    ", gamezop_url, R.drawable.ra14));
        arrayList.add(new Games("lightning-speed2   ", quezop_url, R.drawable.ra15));
        arrayList.add(new Games("Tractor trial    ", gamezop_url, R.drawable.ra16));
        arrayList.add(new Games("Barrel-jump   ", quezop_url, R.drawable.ra17));
        arrayList.add(new Games("Speed-racer    ", gamezop_url, R.drawable.ra18));
        arrayList.add(new Games("Tank-wars     ", quezop_url, R.drawable.ra19));
        arrayList.add(new Games("Track-racer   ", gamezop_url, R.drawable.ra20));
        arrayList.add(new Games("Traffic ", quezop_url, R.drawable.ra21));
        arrayList.add(new Games("Desert Road  ", gamezop_url, R.drawable.ve1));
        arrayList.add(new Games("Drive Taxi     ", quezop_url, R.drawable.ve2));
        arrayList.add(new Games("Maserati GrabTurismo   ", gamezop_url, R.drawable.ve3));
        arrayList.add(new Games("OffRoadClimber   ", quezop_url, R.drawable.ve4));
        arrayList.add(new Games("Buggy Rally     ", gamezop_url, R.drawable.ve5));
        arrayList.add(new Games("Car Speed Booster    ", quezop_url, R.drawable.ve6));
        arrayList.add(new Games("Stud-rider  ", gamezop_url, R.drawable.ve7));
        arrayList.add(new Games("Ninja-jump-force   ", quezop_url, R.drawable.ve8));
        arrayList.add(new Games("Biggy_way   ", gamezop_url, R.drawable.ve9));
        arrayList.add(new Games("Railrush    ", quezop_url, R.drawable.ve10));
        arrayList.add(new Games("Super Speed  Runner    ", gamezop_url, R.drawable.ve12));
        arrayList.add(new Games("TrainGenerationVS   ", quezop_url, R.drawable.ve13));
        arrayList.add(new Games("OffRoadClimber    ", gamezop_url, R.drawable.ve14));
        arrayList.add(new Games("Monster_truck   ", gamezop_url, R.drawable.ve15));
        arrayList.add(new Games("Jelly-slice.         ", quezop_url, R.drawable.an1));
        arrayList.add(new Games("Knife-hit  ", gamezop_url, R.drawable.an2));
        arrayList.add(new Games(" Scooby to Birthday      ", quezop_url, R.drawable.an3));
        arrayList.add(new Games("Spot   The Differences       ", gamezop_url, R.drawable.an4));
        arrayList.add(new Games("Criatures Defence  ", quezop_url, R.drawable.an5));
        arrayList.add(new Games("Harmonica Hopper          ", gamezop_url, R.drawable.an6));
        arrayList.add(new Games("Emoji Glass,      ", quezop_url, R.drawable.an7));
        arrayList.add(new Games(" Baby-Taylor-Farm-Fun         ", gamezop_url, R.drawable.an8));
        arrayList.add(new Games("Babby Anna A days        ", quezop_url, R.drawable.an9));
        arrayList.add(new Games("Wash  pets        ", gamezop_url, R.drawable.an10));
        arrayList.add(new Games("Meng Chong Cheng     ", quezop_url, R.drawable.an11));
        arrayList.add(new Games("My Dolffin  Show       ", gamezop_url, R.drawable.an12));
        arrayList.add(new Games("Meow Dress Up         ", quezop_url, R.drawable.an13));
        arrayList.add(new Games("Victoria Adopts a Kitten        ", gamezop_url, R.drawable.an14));
        arrayList.add(new Games("MatchAnimals ", quezop_url, R.drawable.an15));
        arrayList.add(new Games("Fish-world-match ", gamezop_url, R.drawable.an16));
        arrayList.add(new Games("brain-test-tricky ", quezop_url, R.drawable.qz1));
        arrayList.add(new Games("millionaire-quiz ", gamezop_url, R.drawable.qz2));
        arrayList.add(new Games(" math-quiz", quezop_url, R.drawable.qz3));
        arrayList.add(new Games("Mastermind ", gamezop_url, R.drawable.qz4));
        arrayList.add(new Games(" Europe-flag-quiz", quezop_url, R.drawable.qz5));
        arrayList.add(new Games("Guess-who-tps ", gamezop_url, R.drawable.qz6));
        arrayList.add(new Games("crazy_jump ", quezop_url, R.drawable.u1));
        arrayList.add(new Games("fruit-break ", gamezop_url, R.drawable.u2));
        arrayList.add(new Games("piano-tiles-classic ", quezop_url, R.drawable.u3));
        arrayList.add(new Games("stick-santa ", gamezop_url, R.drawable.u4));
        arrayList.add(new Games(" finger-drift", quezop_url, R.drawable.u5));
        arrayList.add(new Games("candy-match-saga ", gamezop_url, R.drawable.u6));
        arrayList.add(new Games("two-gun ", quezop_url, R.drawable.u7));
        arrayList.add(new Games(" pow", gamezop_url, R.drawable.u8));
        arrayList.add(new Games(" dentist-doctor-teeth", quezop_url, R.drawable.u9));
        arrayList.add(new Games("pipe-mania ", gamezop_url, R.drawable.u11));
        arrayList.add(new Games(" tic-tac-toe", quezop_url, R.drawable.u12));
        arrayList.add(new Games("wheelie-bike", gamezop_url, R.drawable.u13));
        arrayList.add(new Games(" cross-word", quezop_url, R.drawable.u14));
        arrayList.add(new Games("mario-adventure-worlds", gamezop_url, R.drawable.u16));
        arrayList.add(new Games("monster_truck ", quezop_url, R.drawable.u17));
        arrayList.add(new Games(" moto_beach_rider", gamezop_url, R.drawable.u18));
        arrayList.add(new Games("uzzle_ball ", gamezop_url, R.drawable.u19));
        arrayList.add(new Games(" checker-master", quezop_url, R.drawable.u20));
        arrayList.add(new Games("chess-master ", gamezop_url, R.drawable.u21));
        arrayList.add(new Games(" stickman-ping-pong", quezop_url, R.drawable.u22));
        arrayList.add(new Games(" 100-balls", gamezop_url, R.drawable.u23));
        arrayList.add(new Games("3d-rubiks-cube ", quezop_url, R.drawable.u24));
        arrayList.add(new Games("christmas-brickout ", gamezop_url, R.drawable.u25));
        arrayList.add(new Games(" cut-the-rope", quezop_url, R.drawable.u26));
        arrayList.add(new Games(" santa-christmas-adventure", gamezop_url, R.drawable.u27));
        arrayList.add(new Games("spinner-vs-zombies ", quezop_url, R.drawable.u28));
        arrayList.add(new Games("young-santa ", gamezop_url, R.drawable.u29));
        arrayList.add(new Games(" word-connect", quezop_url, R.drawable.u30));
        arrayList.add(new Games(" ocean-fishing", gamezop_url, R.drawable.u31));
        arrayList.add(new Games("  gold-miner-jack", quezop_url, R.drawable.u32));
        arrayList.add(new Games(" e.t ", gamezop_url, R.drawable.u33));
        arrayList.add(new Games(" bad-roll-piggies", quezop_url, R.drawable.u34));
        arrayList.add(new Games("Tomb-runner-2 ", gamezop_url, R.drawable.u35));
        arrayList.add(new Games("unlock-block ", quezop_url, R.drawable.u36));
        arrayList.add(new Games("  dunk-line", gamezop_url, R.drawable.u37));
        arrayList.add(new Games("  ultimate-sudoku", gamezop_url, R.drawable.u38));
        arrayList.add(new Games(" monster_truck", quezop_url, R.drawable.u39));
        arrayList.add(new Games("redboy-and-bluegirl", gamezop_url, R.drawable.u41));
        arrayList.add(new Games(" 8-ball-pool ", quezop_url, R.drawable.u42));
        arrayList.add(new Games("  knife-ninja", gamezop_url, R.drawable.u43));
        arrayList.add(new Games("  slither.io", quezop_url, R.drawable.u44));
        arrayList.add(new Games(" pixels-art-hero ", gamezop_url, R.drawable.u45));
        arrayList.add(new Games("archery_training  ", quezop_url, R.drawable.u46));
        arrayList.add(new Games("  table-tennis-world-tour", gamezop_url, R.drawable.u47));
        arrayList.add(new Games(" christmas-santas-mission ", quezop_url, R.drawable.u49));
        arrayList.add(new Games(" shark-adventure ", gamezop_url, R.drawable.u50));
        arrayList.add(new Games("angry-birds", quezop_url, R.drawable.u53));
        arrayList.add(new Games(" guitar-hero ", quezop_url, R.drawable.u54));
        arrayList.add(new Games("neon-hockey ", gamezop_url, R.drawable.u56));
        arrayList.add(new Games("christmas-santa-dream ", gamezop_url, R.drawable.u55));
        arrayList.add(new Games("christmas-santa-bomber ", quezop_url, R.drawable.u57));
        arrayList.add(new Games(" basketball frvr", gamezop_url, R.drawable.u58));
        arrayList.add(new Games("bottle-flip ", quezop_url, R.drawable.u59));
        arrayList.add(new Games(" fidget-spinner", gamezop_url, R.drawable.u60));
        arrayList.add(new Games("zig-music-line ", quezop_url, R.drawable.u61));
        arrayList.add(new Games(" hex-puzzle", gamezop_url, R.drawable.u62));
        arrayList.add(new Games("flappy-dunk", quezop_url, R.drawable.u63));
        arrayList.add(new Games("impossible-dash-online", quezop_url, R.drawable.u64));
        arrayList.add(new Games("color-jump ", gamezop_url, R.drawable.u65));
        arrayList.add(new Games(" finger-drift", quezop_url, R.drawable.u66));
        arrayList.add(new Games(" tap-touch-run", gamezop_url, R.drawable.u67));
        arrayList.add(new Games("moto-winter ", quezop_url, R.drawable.u68));
        arrayList.add(new Games(" shoot-balls-3d", gamezop_url, R.drawable.u69));
        arrayList.add(new Games(" highway-rider-extrem", gamezop_url, R.drawable.u71));
        arrayList.add(new Games(" santa-christmas-adventure", quezop_url, R.drawable.u72));
        arrayList.add(new Games(" skate hooligan", gamezop_url, R.drawable.u74));
        arrayList.add(new Games("mini-drifts ", quezop_url, R.drawable.u73));
        arrayList.add(new Games(" krishna-jump", gamezop_url, R.drawable.u81));
        arrayList.add(new Games("jungle-bricks ", quezop_url, R.drawable.u82));
        arrayList.add(new Games("cricket 2020 ", gamezop_url, R.drawable.u83));
        arrayList.add(new Games("street-cricket", quezop_url, R.drawable.u84));
        arrayList.add(new Games("thank-you-santa ", gamezop_url, R.drawable.u85));
        arrayList.add(new Games("feedh bobo ", quezop_url, R.drawable.u86));
        arrayList.add(new Games("cricket world cup ", gamezop_url, R.drawable.u87));
        arrayList.add(new Games(" guns and bottles", quezop_url, R.drawable.u88));
        arrayList.add(new Games(" runpanda run", gamezop_url, R.drawable.u89));
        arrayList.add(new Games("piggy-night ", quezop_url, R.drawable.u90));
        arrayList.add(new Games("pingu-and-friends ", gamezop_url, R.drawable.u91));
        arrayList.add(new Games(" Hit the glow ", quezop_url, R.drawable.u92));
        arrayList.add(new Games("jumpy-kangaroo ", gamezop_url, R.drawable.u93));
        arrayList.add(new Games("caveman-adventures5 ", quezop_url, R.drawable.u94));
        arrayList.add(new Games(" squirrel-hop", gamezop_url, R.drawable.u95));
        arrayList.add(new Games(" tomato-crusher", quezop_url, R.drawable.u96));
        arrayList.add(new Games(" maze-lover", gamezop_url, R.drawable.u97));
        arrayList.add(new Games(" sumo-saga", quezop_url, R.drawable.u98));
        arrayList.add(new Games(" stud-rider", gamezop_url, R.drawable.u99));
        arrayList.add(new Games(" ninja-action", quezop_url, R.drawable.u100));
        arrayList.add(new Games("soldiers-combat ", gamezop_url, R.drawable.u101));
        arrayList.add(new Games(" village-story", quezop_url, R.drawable.u102));
        arrayList.add(new Games(" airplane-battle", gamezop_url, R.drawable.u103));
        arrayList.add(new Games("the-office-guy ", quezop_url, R.drawable.u104));
        arrayList.add(new Games("speedy-boat ", gamezop_url, R.drawable.u105));
        arrayList.add(new Games(" light-rays", quezop_url, R.drawable.u106));
        arrayList.add(new Games("egypt-stone-war ", gamezop_url, R.drawable.u107));
        arrayList.add(new Games(" robbers-in-town", quezop_url, R.drawable.u108));
        arrayList.add(new Games(" poop-it", gamezop_url, R.drawable.u109));
        arrayList.add(new Games("robbers-in-town ", quezop_url, R.drawable.u110));
        arrayList.add(new Games(" dino-jump", gamezop_url, R.drawable.u111));
        arrayList.add(new Games(" flyingturtle", quezop_url, R.drawable.u112));
        arrayList.add(new Games("Cupid Heard ", gamezop_url, R.drawable.u113));
        arrayList.add(new Games(" forest-warrior", quezop_url, R.drawable.u114));
        arrayList.add(new Games("mrpotato ", gamezop_url, R.drawable.u115));
        arrayList.add(new Games("road-fight ", quezop_url, R.drawable.u116));
        arrayList.add(new Games(" bounce-ball", gamezop_url, R.drawable.u117));
        arrayList.add(new Games("Ludo multiplayers ", quezop_url, R.drawable.u118));
        arrayList.add(new Games(" monsters-up", gamezop_url, R.drawable.u119));
        arrayList.add(new Games("jully Jump ", quezop_url, R.drawable.u120));
        arrayList.add(new Games(" goblins-vs-skeleton", gamezop_url, R.drawable.u121));
        arrayList.add(new Games("jungle-war ", quezop_url, R.drawable.u122));
        arrayList.add(new Games(" swing-robber", gamezop_url, R.drawable.u123));
        arrayList.add(new Games(" rise-up", quezop_url, R.drawable.u124));
        arrayList.add(new Games("mini-jump ", gamezop_url, R.drawable.u125));
        arrayList.add(new Games("Dotted alphabet", quezop_url, R.drawable.u126));
        arrayList.add(new Games("rocket-lizard ", gamezop_url, R.drawable.u127));
        arrayList.add(new Games("Captain war ", quezop_url, R.drawable.u128));
        arrayList.add(new Games(" sea ship Rasing", gamezop_url, R.drawable.u129));
        arrayList.add(new Games(" Incredible ninja ", quezop_url, R.drawable.u130));
        arrayList.add(new Games("Chase rasing cars ", gamezop_url, R.drawable.u131));
        arrayList.add(new Games("mashroom fall ", quezop_url, R.drawable.u132));
        arrayList.add(new Games(" jungle slump", gamezop_url, R.drawable.u133));
        arrayList.add(new Games("Cowboy Shoot Zombie ", quezop_url, R.drawable.u134));
        arrayList.add(new Games("ogre Defense ", gamezop_url, R.drawable.u135));
        arrayList.add(new Games("tom-skate ", quezop_url, R.drawable.u136));
        arrayList.add(new Games(" Shoot Angry Zombie", gamezop_url, R.drawable.u137));
        arrayList.add(new Games("School boy Warrior ", quezop_url, R.drawable.u138));
        arrayList.add(new Games(" Monkey banana Jump", gamezop_url, R.drawable.u139));
        arrayList.add(new Games("Captain war Z.K ", quezop_url, R.drawable.u140));
        arrayList.add(new Games("fall jump Roll ", gamezop_url, R.drawable.u141));
        arrayList.add(new Games(" Dubble Sticman", quezop_url, R.drawable.u142));
        arrayList.add(new Games("Bazooka gun boy ", gamezop_url, R.drawable.u143));
        arrayList.add(new Games(" Jumpng Angry Ape", quezop_url, R.drawable.u144));
        arrayList.add(new Games("Cut Monester Jum ", gamezop_url, R.drawable.u145));
        arrayList.add(new Games(" Car Speed Booster", quezop_url, R.drawable.u146));
        arrayList.add(new Games("Angry Dragons ", gamezop_url, R.drawable.u147));
        arrayList.add(new Games(" Defenders Mission", quezop_url, R.drawable.u148));
        arrayList.add(new Games(" Fighting aircraft battle", gamezop_url, R.drawable.u149));
        return arrayList;
    }
}